<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Voucher extends Model
{
    use HasFactory;

    protected $fillable = [
        'router_id',
        'package_id',
        'created_by',
        'username',
        'password',
        'batch_code',
        'status',
        'first_login_at',
        'expires_at',
        'used_by_mac',
        'sold_price',
        'sold_at',
        'comment',
    ];

    protected $casts = [
        'first_login_at' => 'datetime',
        'expires_at' => 'datetime',
        'sold_at' => 'datetime',
        'sold_price' => 'decimal:2',
    ];

    public function router()
    {
        return $this->belongsTo(Router::class);
    }

    public function package()
    {
        return $this->belongsTo(Package::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function sale()
    {
        return $this->hasOne(Sale::class);
    }

    /**
     * ভাউচার জেনারেট করুন
     */
    public static function generate(
        int $routerId,
        int $packageId,
        int $createdBy,
        int $quantity = 1,
        string $prefix = '',
        int $usernameLength = 8,
        int $passwordLength = 8,
        string $userMode = 'voucher' // voucher or user_pass
    ): array {
        $vouchers = [];
        $batchCode = Str::upper(Str::random(8));
        $characters = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'; // Confusing chars removed

        for ($i = 0; $i < $quantity; $i++) {
            $username = $prefix;
            $password = '';

            // Generate username
            for ($j = 0; $j < $usernameLength; $j++) {
                $username .= $characters[random_int(0, strlen($characters) - 1)];
            }

            // Generate password (same as username for voucher mode)
            if ($userMode === 'voucher') {
                $password = $username;
            } else {
                for ($j = 0; $j < $passwordLength; $j++) {
                    $password .= $characters[random_int(0, strlen($characters) - 1)];
                }
            }

            $vouchers[] = self::create([
                'router_id' => $routerId,
                'package_id' => $packageId,
                'created_by' => $createdBy,
                'username' => $username,
                'password' => $password,
                'batch_code' => $batchCode,
                'status' => 'unused',
            ]);
        }

        return $vouchers;
    }

    /**
     * MikroTik এ সিঙ্ক করুন
     */
    public function syncToMikrotik(): bool
    {
        $api = $this->router->getApi();
        
        if (!$api->connect()) {
            return false;
        }

        $result = $api->addHotspotUser(
            $this->username,
            $this->password,
            $this->package->mikrotik_profile,
            $this->comment ?? 'Generated by SKYNITY',
            $this->package->validity,
            $this->package->data_limit
        );

        $api->disconnect();
        
        return $result;
    }

    /**
     * স্ট্যাটাস লেবেল পান
     */
    public function getStatusLabelAttribute(): string
    {
        return match($this->status) {
            'unused' => 'অব্যবহৃত',
            'used' => 'ব্যবহৃত',
            'expired' => 'মেয়াদ শেষ',
            'disabled' => 'নিষ্ক্রিয়',
            default => $this->status,
        };
    }

    /**
     * স্ট্যাটাস কালার পান
     */
    public function getStatusColorAttribute(): string
    {
        return match($this->status) {
            'unused' => 'green',
            'used' => 'blue',
            'expired' => 'red',
            'disabled' => 'gray',
            default => 'gray',
        };
    }
}
